In [ ]:
import torch
import torch.nn as nn

In [5]:
import torch.nn as nn 
# vocab_size is the number of words in your train, val and test set
# vector_size is the dimension of the word vectors you are using

vocab_size=25002
vector_size=100

embed = nn.Embedding(vocab_size, vector_size)

In [15]:
tensors = torch.LongTensor([40,64])

In [16]:
tensors

tensor([40, 64])

In [17]:
embed(tensors)

tensor([[ 0.6907,  0.2885,  1.4397,  2.1910, -2.1546,  0.5047,  0.2103, -0.2791,
         -1.0564,  0.5220,  1.2948, -0.5820,  0.5073, -0.0403,  0.7851, -0.5532,
          1.8118,  0.0442,  1.8285,  0.7730,  0.3019,  1.2317, -0.6490,  1.6030,
         -0.1088,  1.0509, -0.6375, -0.5121,  1.6826, -1.0671, -0.2840,  1.6584,
         -0.5461,  1.2828, -0.8427, -0.6241,  1.5092, -0.2173,  0.6912, -0.0040,
         -0.3063, -1.5882, -0.0471, -1.8819,  0.0270,  0.1458, -0.1377,  0.0088,
          0.7891, -0.4372,  0.7212, -0.1882,  2.6015, -1.4048, -0.8014,  0.3659,
         -1.0742, -0.0092,  1.2280,  0.3879,  0.3928,  0.7381, -0.9672, -0.6976,
          1.5110,  0.0171, -0.0420, -0.1572, -0.7460, -0.6266, -1.4129, -0.4456,
          0.0652,  0.0281,  0.7886, -0.3335,  0.5035,  0.5686,  1.7987, -0.4270,
         -0.3612, -0.1875, -0.5128,  0.6400, -0.4544, -0.1112, -0.4476, -0.1953,
         -0.5148, -0.3685, -1.2785,  0.2937, -0.6769,  0.1851, -0.3565,  0.6629,
          1.4697, -1.2253,  

In [9]:
list(embed.parameters())

[Parameter containing:
 tensor([[ 0.6784, -0.4624, -1.4364,  ..., -0.9431,  0.5979,  1.3909],
         [ 0.7087, -1.8524,  1.2147,  ..., -0.0700,  1.1300, -1.7908],
         [ 0.0802, -0.1246,  0.2650,  ...,  1.9817,  1.6588,  0.4340],
         ...,
         [ 0.6061,  1.1936,  0.7391,  ..., -0.0692, -1.4160,  0.6841],
         [ 1.2195,  1.0505, -0.7947,  ...,  1.7236, -0.8602,  1.9560],
         [-0.3548, -0.8418,  0.6386,  ..., -0.5770,  1.0387,  1.4710]],
        requires_grad=True)]

In [176]:
class lstm(nn.Module):
    
    def __init__(self):
        
        super(lstm , self).__init__()
        
        self.lstm = nn.LSTM(in_size , classes_no , batch_first=True)
        
    def forward(self,x):
        
        print(f'x size: {x.size()}')
        
        out , _ = self.lstm(x)
        
        print(out[:,-1])

In [177]:
#size 10,3,7
batch_size=3
time_steps=10
in_size=5
classes_no=2

input_seq = torch.randn(batch_size , time_steps , in_size)

In [178]:
model = lstm()

In [179]:
out=  model(input_seq)

x size: torch.Size([3, 10, 5])
tensor([[ 0.2158,  0.6023],
        [ 0.1530, -0.0690],
        [ 0.1036,  0.3327]], grad_fn=<SelectBackward>)
